# Generated by Django 4.2 on 2023-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrmodel',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
